---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: default
  resourceVersion: "516"
data:
  application-mysql2.properties: |
    database=mysql
    spring.datasource.url=jdbc:mysql://10.0.3.237/petclinic
    spring.datasource.username=petclinic
    spring.datasource.password=petclinic
    spring.datasource.initialization-mode=always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    tier: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: petclinic
  template:
    metadata:
      labels:
        tier: petclinic
    spec:
      containers:
      - name: petclinic
        image: mrpipikado/petclinic:petclinic
        ports:
        - containerPort: 8080
          name: "http-server"
        command: ["java"]
        args: ["-jar", "/tmp/app.jar","--spring.config.location=file:///tmp/config/application-mysql2.properties", "--spring.profiles.active=mysql2"]
        volumeMounts:
        - name: petclinic-conf
          mountPath: /tmp/config
      volumes:
      - name: petclinic-conf
        configMap:
          name: petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-lb
spec:
  selector:
    tier: petclinic
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
