apiVersion: v1
data:
  application-mysql2.properties: ZGF0YWJhc2U9bXlzcWwKc3ByaW5nLmRhdGFzb3VyY2UudXJsPWpkYmM6bXlzcWw6Ly9teXNxbC9wZXRjbGluaWMKc3ByaW5nLmRhdGFzb3VyY2UudXNlcm5hbWU9cGV0Y2xpbmljCnNwcmluZy5kYXRhc291cmNlLnBhc3N3b3JkPXBldGNsaW5pYwpzcHJpbmcuZGF0YXNvdXJjZS5pbml0aWFsaXphdGlvbi1tb2RlPWFsd2F5cwpzcHJpbmcubWVzc2FnZXMuYmFzZW5hbWU9bWVzc2FnZXMvbWVzc2FnZXMK
kind: Secret
metadata:
  name: app-profile
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    tier: petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: petclinic
  template:
    metadata:
      labels:
        tier: petclinic
    spec:
      containers:
      - name: petclinic
        image: mrpipikado/final_project:latest
        ports:
        - containerPort: 8080
          name: "http-server"
        command: ["java"]
        args: ["-jar", "/tmp/app.jar","--spring.config.location=file:///tmp/config/application-mysql2.properties", "--spring.profiles.active=mysql2"]
        volumeMounts:
        - name: petclinic-conf
          mountPath: /tmp/config
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      volumes:
      - name: petclinic-conf
        secret:
          secretName: app-profile
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-lb
spec:
  selector:
    tier: petclinic
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
