---
apiVersion: v1
data:
  application-mysql2.properties: ZGF0YWJhc2U9bXlzcWwKc3ByaW5nLmRhdGFzb3VyY2UudXJsPWpkYmM6bXlzcWw6Ly8xMC4wLjMuMTQwL3BldGNsaW5pYwpzcHJpbmcuZGF0YXNvdXJjZS51c2VybmFtZT1wZXRjbGluaWMKc3ByaW5nLmRhdGFzb3VyY2UucGFzc3dvcmQ9cGV0Y2xpbmljCnNwcmluZy5kYXRhc291cmNlLmluaXRpYWxpemF0aW9uLW1vZGU9YWx3YXlzCg==
kind: Secret
metadata:
  name: petclinic-config
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    tier: petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: petclinic
  template:
    metadata:
      labels:
        tier: petclinic
    spec:
      containers:
      - name: petclinic
        image: mrpipikado/final:latest
        ports:
        - containerPort: 8080
          name: "http-server"
        command: ["java"]
        args: ["-jar", "/tmp/app.jar","--spring.config.location=file:///tmp/config/application-mysql2.properties", "--spring.profiles.active=mysql2"]
        volumeMounts:
        - name: petclinic-conf
          mountPath: /tmp/config
      volumes:
      - name: petclinic-conf
        secret:
          secretName: petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-lb
spec:
  selector:
    tier: petclinic
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
